import { z } from 'zod'
import {
  evidenceLineageSchema,
  orchestrationLineageSchema,
  runTimelineItemSchema,
  versionLineageSchema,
  evolutionJobSchema,
  evolutionJobCountsSchema,
  evolutionJobCreateSchema,
  operationsOverviewSchema,
  runtimeModeSchema,
  serviceHeartbeatSchema,
  candidateProposalSchema,
  capabilityOperationSchema,
  evolutionPlanningContextSchema,
  searchEvidenceSchema,
  searchQuerySchema,
  searchResultSchema,
  sourceOperationSchema,
  evolutionCandidateSummarySchema,
  horizonOutcomeViewSchema,
  requirementReadinessItemSchema,
  researchCostBreakdownSchema,
  researchCostComponentSchema,
  researchInboxItemSchema,
  researchInboxViewSchema,
  researchObservabilityViewSchema,
  researchValueEvaluationSchema,
  researchVersionLineageSchema,
  sourceAttemptViewSchema,
} from './generated/r2'

export {
  dshBridgeErrorSchema,
  dshBusinessFailureSchema,
  dshBusinessStatusSchema,
  dshBrowserStatusSchema,
  dshHostReadinessSchema,
  dshResearchIntakeAcceptedSchema,
  dshResearchIntakeSchema,
  dshRunSessionLinkViewSchema,
  dshSessionAcceptedSchema,
  dshSessionCompletionSchema,
  dshSessionPromptSchema,
  dshSessionResultSchema,
  dshSessionStatusSchema,
  dshSessionSubmitSchema,
  dshUpstreamIdentitySchema,
  causalCaseSchema,
  causalLinkSchema,
  conflictItemSchema,
  coverageAssessmentSchema,
  domainPackManifestSchema,
  evidenceCandidateSchema,
  evidenceGapSchema,
  evidenceRequirementSchema,
  executionBudgetSchema,
  horizonDecisionSchema,
  productExtensionManifestSchema,
  errorProvenanceSchema,
  researchCapabilityQuerySchema,
  researchCapabilityManifestSchema,
  researchCapabilityResultSchema,
  researchInputEvidenceSchema,
  researchPlanSchema,
  researchRoundSchema,
  researchRunCommandSchema,
  researchRunCommandResultSchema,
  researchRunDetailViewSchema,
  researchRunQueuedSchema,
  researchRunViewSchema,
  researchSessionRequestSchema,
  researchSessionResultSchema,
  researchSynthesisCandidateSchema,
  researchStopReasonSchema,
  researchTaskSchema,
  researchTraceEventSchema,
  roleProfileSchema,
  toolInvocationSchema,
  toolResultSummarySchema,
} from './generated/r2'

export type {
  DshBridgeError,
  DshBusinessFailure,
  DshBusinessStatus,
  DshBrowserStatus,
  DshHostReadiness,
  DshResearchIntake,
  DshResearchIntakeAccepted,
  DshRunSessionLinkView,
  DshSessionAccepted,
  DshSessionCompletion,
  DshSessionPrompt,
  DshSessionResult,
  DshSessionStatus,
  DshSessionSubmit,
  DshUpstreamIdentity,
  CausalCase,
  CausalLink,
  ConflictItem,
  CoverageAssessment,
  DomainPackManifest,
  EvidenceCandidate,
  EvidenceGap,
  EvidenceRequirement,
  ExecutionBudget,
  HorizonDecision,
  ProductExtensionManifest,
  ProviderAttempt,
  ProviderRoute,
  ResearchCapabilityManifest,
  ResearchInputEvidence,
  ResearchPlan,
  ResearchRound,
  ResearchRunCommand,
  ResearchRunCommandResult,
  ResearchRunDetailView,
  ResearchRunQueued,
  ResearchRunView,
  ResearchSessionRequest,
  ResearchSessionResult,
  ResearchSynthesisCandidate,
  ResearchStopReason,
  ResearchTask,
  ResearchTraceEvent,
  RoleProfile,
  ToolInvocation,
  ToolResultSummary,
} from './generated/r2'

export {
  activePointerSchema,
  candidateVersionSchema,
  capabilityManifestSchema,
  evaluationDatasetSchema,
  evolutionOverviewSchema,
  experienceCreateSchema,
  experienceSchema,
  experimentResultSchema,
  experimentSchema,
  failurePatternSchema,
  feedbackCreateSchema,
  feedbackSchema,
  promotionDecisionCommandSchema,
  promotionDecisionResultSchema,
  promotionDecisionSchema,
  promotionGateCheckSchema,
  promotionMetricDeltaSchema,
  promotionReviewRequestSchema,
  promotionReviewSchema,
  researchMemoCreateSchema,
  researchMemoSchema,
  workbenchOverviewSchema,
  evolutionJobSchema,
  evolutionJobCountsSchema,
  evolutionJobCreateSchema,
  operationsOverviewSchema,
  runtimeModeSchema,
  serviceHeartbeatSchema,
  candidateProposalSchema,
  capabilityOperationSchema,
  evolutionPlanningContextSchema,
  searchEvidenceSchema,
  searchQuerySchema,
  searchResultSchema,
  sourceOperationSchema,
  evolutionCandidateSummarySchema,
  horizonOutcomeViewSchema,
  requirementReadinessItemSchema,
  researchCostBreakdownSchema,
  researchCostComponentSchema,
  researchInboxItemSchema,
  researchInboxViewSchema,
  researchObservabilityViewSchema,
  researchValueEvaluationSchema,
  researchVersionLineageSchema,
  sourceAttemptViewSchema,
  evidenceLineageSchema,
  orchestrationLineageSchema,
  runTimelineItemSchema,
  versionLineageSchema,
} from './generated/r2'

export const runStatusSchema = z.enum(['admitted', 'running', 'completed', 'degraded', 'failed', 'cancelled'])
export const gateStatusSchema = z.enum(['publish', 'degraded', 'research_only', 'reject'])
export const directionSchema = z.enum(['long', 'short', 'neutral', 'no_trade'])
export const sourceManifestSchema = z.object({
  source_id: z.string().min(1), source_type: z.string().min(1), version: z.string().min(1),
  capabilities: z.array(z.string()), authority_level: z.string(),
  poll_interval_seconds: z.number().positive(), max_batch: z.number().int().positive(),
  allowed_domains: z.array(z.string()).default([]), enabled: z.boolean(),
})
export const sourceHealthSchema = z.object({
  source_id: z.string(), status: z.string(), cursor: z.string().nullable(),
  last_success_at: z.string().nullable(), last_error_at: z.string().nullable(),
  consecutive_failures: z.number().int().nonnegative(), latency_ms: z.number().nullable(),
  error_code: z.string().nullable(), next_poll_at: z.string().nullable(),
})
export const marketQuoteSchema = z.object({
  instrument: z.string(), observed_at: z.string(), received_at: z.string(),
  bid: z.number().nullable(), ask: z.number().nullable(), last: z.number().nullable(),
  volume: z.number().nullable(), source_id: z.string(),
  quality_status: z.enum(['observed', 'estimated', 'unavailable']),
  benchmark: z.enum(['first_executable', 'vwap_1m', 'last', 'none']),
})
export const notificationMessageSchema = z.object({
  artifact_id: z.string(), channel: z.string(), dedupe_key: z.string(),
  subject: z.string(), body: z.string(), created_at: z.string(),
})
export const productHealthSchema = z.object({
  status: z.enum(['ok', 'degraded']), running_runs: z.number().int().nonnegative(),
  failed_runs: z.number().int().nonnegative(), sources: z.array(sourceHealthSchema),
})
export const pilotReadinessCheckSchema = z.object({
  check_id: z.string().min(1), status: z.enum(['pass', 'fail', 'warning']),
  detail: z.string().min(1), error_code: z.string().nullable(),
})
export const pilotReadinessReportSchema = z.object({
  schema_version: z.literal('pilot-readiness.v1'), status: z.enum(['ready', 'not_ready']),
  checked_at: z.string(), pilot_mode: z.boolean(),
  notification_channel: z.enum(['local', 'email']), source_ids: z.array(z.string()),
  checks: z.array(pilotReadinessCheckSchema), live_canaries_required: z.array(z.string()),
})

export const forecastSchema = z.object({
  forecast_id: z.string(), artifact_id: z.string(), instrument: z.string(), horizon: z.string(),
  direction: directionSchema, probability: z.number().min(0).max(1), trigger: z.string(),
  invalidation: z.string(), expires_at: z.string(),
})

export const runViewSchema = z.object({
  run_id: z.string(), event_id: z.string(), status: runStatusSchema, strategy_version: z.string(), runtime_version: z.string().default('unknown'),
  snapshot_id: z.string().nullable(), artifact_id: z.string().nullable(), created_at: z.string(),
  updated_at: z.string(), finished_at: z.string().nullable(), latency_ms: z.number().nullable(),
  cost_usd: z.number().nullable(), error_code: z.string().nullable(), headline: z.string().nullable(),
  gate_status: gateStatusSchema.nullable(),
})

export const artifactViewSchema = z.object({
  artifact_id: z.string(), run_id: z.string(), event_id: z.string(), gate_status: gateStatusSchema,
  headline: z.string(), summary: z.string(), facts: z.array(z.string()), inferences: z.array(z.string()),
  counter_thesis: z.string(), uncertainty: z.array(z.string()), transmission_chain: z.array(z.string()),
  citations: z.array(z.string()), forecasts: z.array(forecastSchema),
  gate_decisions: z.array(z.object({ rule_id: z.string(), status: z.string(), reason_code: z.string(), input_hash: z.string() })),
  created_at: z.string(),
})

export const deskSummarySchema = z.object({
  inbox: z.object({ pending_count: z.number(), running_count: z.number(), latest: z.array(runViewSchema) }),
  published_count_30d: z.number(), forecast_count: z.number(), evaluated_count: z.number(),
  health_status: z.string(), active_strategy: z.string(), active_pack: z.string(),
})

export const callViewSchema = z.object({
  call_id: z.string(), run_id: z.string(), role: z.string(), status: z.string(), attempt: z.number(),
  started_at: z.string(), finished_at: z.string().nullable(), latency_ms: z.number().nullable(),
  runtime_id: z.string().nullable(), runtime_version: z.string().nullable(), provider_id: z.string().nullable(),
  model: z.string().nullable(), api_mode: z.string().nullable(), schema_version: z.string().nullable(),
  prompt_tokens: z.number().nullable(), completion_tokens: z.number().nullable(), total_tokens: z.number().nullable(),
  cost_usd: z.number().nullable(), cost_status: z.string(), pricing_version: z.string().nullable(),
  error_code: z.string().nullable(), retryable: z.boolean(),
})

export const stepViewSchema = z.object({
  step_id: z.string(), run_id: z.string(), step_name: z.string(), status: z.string(),
  attempt: z.number(), started_at: z.string(), finished_at: z.string().nullable(),
  latency_ms: z.number().nullable(), error_code: z.string().nullable(),
})

export const runInspectorSchema = z.object({
  run: runViewSchema,
  timeline: z.array(runTimelineItemSchema),
  steps: z.array(stepViewSchema),
  calls: z.array(callViewSchema),
  artifact: artifactViewSchema.nullable(),
  evaluation_count: z.number(),
  evaluations: z.array(z.object({
    evaluation_id: z.string(), forecast_id: z.string(), brier_score: z.number(),
    net_return_pct: z.number(), direction_correct: z.boolean(), label_status: z.string(), evaluated_at: z.string(),
  })),
  snapshot_cutoff_at: z.string().nullable(),
  snapshot_hash: z.string().nullable(),
  evidence_lineage: z.array(evidenceLineageSchema),
  versions: versionLineageSchema,
  orchestration: orchestrationLineageSchema,
}).strict()

export type Forecast = z.infer<typeof forecastSchema>
export type GateStatus = z.infer<typeof gateStatusSchema>
export type RunView = z.infer<typeof runViewSchema>
export type ArtifactView = z.infer<typeof artifactViewSchema>
export type DeskSummary = z.infer<typeof deskSummarySchema>
export type CallView = z.infer<typeof callViewSchema>
export type StepView = z.infer<typeof stepViewSchema>
export type RunInspector = z.infer<typeof runInspectorSchema>
export type SourceManifest = z.infer<typeof sourceManifestSchema>
export type SourceHealth = z.infer<typeof sourceHealthSchema>
export type MarketQuote = z.infer<typeof marketQuoteSchema>
export type NotificationMessage = z.infer<typeof notificationMessageSchema>
export type ProductHealth = z.infer<typeof productHealthSchema>
export type PilotReadinessCheck = z.infer<typeof pilotReadinessCheckSchema>
export type PilotReadinessReport = z.infer<typeof pilotReadinessReportSchema>
export type {
  ActivePointer,
  CandidateVersion,
  CapabilityManifest,
  EvaluationDataset,
  EvidenceLineage,
  EvolutionOverview,
  Experience,
  ExperienceCreate,
  Experiment,
  ExperimentResult,
  FailurePattern,
  Feedback,
  FeedbackCreate,
  OrchestrationLineage,
  PromotionDecision,
  PromotionDecisionCommand,
  PromotionDecisionResult,
  PromotionGateCheck,
  PromotionMetricDelta,
  PromotionReview,
  PromotionReviewRequest,
  ResearchMemo,
  ResearchMemoCreate,
  ResearchCapabilityQuery,
  ResearchCapabilityResult,
  ResearchSnapshotManifest,
  RunTimelineItem,
  VersionLineage,
  WorkbenchOverview,
  EvolutionJob,
  EvolutionJobCounts,
  EvolutionJobCreate,
  OperationsOverview,
  RuntimeMode,
  ServiceHeartbeat,
  CandidateProposal,
  CapabilityOperation,
  EvolutionPlanningContext,
  SearchEvidence,
  SearchQuery,
  SearchResult,
  SourceOperation,
  EvolutionCandidateSummary,
  HorizonOutcomeView,
  RequirementReadinessItem,
  ResearchCostBreakdown,
  ResearchCostComponent,
  ResearchInboxItem,
  ResearchInboxView,
  ResearchObservabilityView,
  ResearchValueEvaluation,
  ResearchVersionLineage,
  SourceAttemptView,
} from './generated/r2'
